language: Python
python: 3.6

env:
  global:
    - HUGO_VERSION=0.55.6


before_install:
  - gem install mdl
  - pip install proselint
  - npm install -g sass
  # install hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz hugo
  # probably don't need this but just to be sure
  - rm -rf hugo_0.55.6_Linux-64bit.tar.gz
  - export PATH="$PWD:$PATH"

script:
  # see all directories
  - shopt -s globstar
  # check writing
  - proselint README.md
  - mdl README.md
  # build
  - hugo
